In [15]:
import numpy as np

In [16]:
np.mat('1 2 3; 4 5 6; 7 8 9')#建矩阵

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
np.mat('1 2 3; 4 5 6; 7 8 9').T#转置

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [18]:
np.mat(np.arange(9).reshape(3,3))#建矩阵 从数组

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [25]:
A = np.eye(2)
B = 2 * A
np.bmat("A B;B A")#建矩阵 从矩阵

matrix([[1., 0., 2., 0.],
        [0., 1., 0., 2.],
        [2., 0., 1., 0.],
        [0., 2., 0., 1.]])

In [29]:
np.zeros_like(np.arange(4))

array([0, 0, 0, 0])

In [31]:
np.zeros_like(np.arange(4).reshape(2,2))#create array by shape

array([[0, 0],
       [0, 0]])

In [34]:
C = np.zeros_like(np.arange(4).reshape(2,2)) 
C.flat = 42 # set value
C

array([[42, 42],
       [42, 42]])

In [35]:
def ultimate_answer(a):
    result = np.zeros_like(a)
    result.flat = 42
    return result
ufunc = np.frompyfunc(ultimate_answer,1,1)
ufunc(np.arange(4))

array([array(42), array(42), array(42), array(42)], dtype=object)

In [36]:
ufunc(np.arange(4).reshape(2,2))

array([[array(42), array(42)],
       [array(42), array(42)]], dtype=object)

In [39]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.add.reduce(np.arange(9))#求和

36

In [38]:
np.add.accumulate(np.arange(9))

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [40]:
np.add.reduceat(np.arange(9),[0, 5, 2, 7])

array([10,  5, 20, 15])

In [41]:
np.add.reduce(np.arange(9)[0:5])

10

In [42]:
np.add.outer(np.arange(3), np.arange(9))#输出两个数组的秩的和

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [49]:
#数组除法

In [50]:
np.divide(np.array([2,6,5]), np.array([1,2,3]))

array([2.        , 3.        , 1.66666667])

In [51]:
np.divide(np.array([1,2,3]), np.array([2,6,5]))

array([0.5       , 0.33333333, 0.6       ])

In [52]:
np.true_divide(np.array([2,6,5]), np.array([1,2,3]))

array([2.        , 3.        , 1.66666667])

In [53]:
np.true_divide(np.array([1,2,3]), np.array([2,6,5]))

array([0.5       , 0.33333333, 0.6       ])

In [54]:
np.floor_divide(np.array([2,6,5]), np.array([1,2,3]))

array([2, 3, 1])

In [55]:
np.floor_divide(np.array([1,2,3]), np.array([2,6,5]))

array([0, 0, 0])

In [59]:
np.array([2,6,5]) / np.array([1,2,3])

array([2.        , 3.        , 1.66666667])

In [60]:
np.array([1,2,3]) / np.array([2,6,5])

array([0.5       , 0.33333333, 0.6       ])

In [61]:
np.array([2,6,5]) // np.array([1,2,3])

array([2, 3, 1])

In [62]:
np.array([1,2,3]) // np.array([2,6,5])

array([0, 0, 0])

In [63]:
#模运算

In [65]:
np.arange(-4, 4)

array([-4, -3, -2, -1,  0,  1,  2,  3])

In [64]:
np.remainder(np.arange(-4, 4), 2)

array([0, 1, 0, 1, 0, 1, 0, 1])

In [66]:
np.mod(np.arange(-4, 4), 2)

array([0, 1, 0, 1, 0, 1, 0, 1])

In [67]:
np.arange(-4, 4) % 2

array([0, 1, 0, 1, 0, 1, 0, 1])

In [68]:
np.fmod(np.arange(-4, 4), 2)

array([ 0, -1,  0, -1,  0,  1,  0,  1])