In [67]:
import numpy as np
import pandas as pd
import datetime as datetime

In [68]:
pd.read_csv('data.csv', header=None).head(100)

0           1  2       3       4       5       6         7
0   AAPL  28-01-2011     344.17  344.40  333.53  336.10  21144800
1   AAPL  31-01-2011     335.80  340.04  334.30  339.32  13473000
2   AAPL  01-02-2011     341.30  345.65  340.98  345.03  15236800
3   AAPL  02-02-2011     344.45  345.25  343.55  344.32   9242600
4   AAPL  03-02-2011     343.80  344.24  338.55  343.44  14064100
5   AAPL  04-02-2011     343.61  346.70  343.51  346.50  11494200
6   AAPL  07-02-2011     347.89  353.25  347.64  351.88  17322100
7   AAPL  08-02-2011     353.68  355.52  352.15  355.20  13608500
8   AAPL  09-02-2011     355.19  359.00  354.87  358.16  17240800
9   AAPL  10-02-2011     357.39  360.00  348.00  354.54  33162400
10  AAPL  11-02-2011     354.75  357.80  353.54  356.85  13127500
11  AAPL  14-02-2011     356.79  359.48  356.71  359.18  11086200
12  AAPL  15-02-2011     359.19  359.97  357.55  359.90  10149000
13  AAPL  16-02-2011     360.80  364.90  360.50  363.13  17184100
14  AAPL  17-02-2011     357.10  360.27  356.52  358.30  18949000
15  AAPL  18-02-2011     358.21  359.50  349.52  350.56  29144500
16  AAPL  22-02-2011     342.05  345.40  337.72  338.61  31162200
17  AAPL  23-02-2011     338.77  344.64  338.61  342.62  23994700
18  AAPL  24-02-2011     344.02  345.15  338.37  342.88  17853500
19  AAPL  25-02-2011     345.29  348.43  344.80  348.16  13572000
20  AAPL  28-02-2011     351.21  355.05  351.12  353.21  14395400
21  AAPL  01-03-2011     355.47  355.72  347.68  349.31  16290300
22  AAPL  02-03-2011     349.96  354.35  348.40  352.12  21521000
23  AAPL  03-03-2011     357.20  359.79  355.92  359.56  17885200
24  AAPL  04-03-2011     360.07  360.29  357.75  360.00  16188000
25  AAPL  07-03-2011     361.11  361.67  351.31  355.36  19504300
26  AAPL  08-03-2011     354.91  357.40  352.25  355.76  12718000
27  AAPL  09-03-2011     354.69  354.76  350.60  352.47  16192700
28  AAPL  10-03-2011     349.69  349.77  344.90  346.67  18138800
29  AAPL  11-03-2011     345.40  352.32  345.00  351.99  16824200

In [69]:
h,i,c,v = np.loadtxt('data.csv', delimiter=',', usecols=(4,5,6,7), unpack=True)

In [70]:
np.average(c, weights=v)#加权平均值

350.5895493532009

In [71]:
np.mean(c)#平均值

351.0376666666667

In [72]:
np.median(c)#中位数

352.055

In [73]:
np.msort(c)#排序

array([336.1 , 338.61, 339.32, 342.62, 342.88, 343.44, 344.32, 345.03,
       346.5 , 346.67, 348.16, 349.31, 350.56, 351.88, 351.99, 352.12,
       352.47, 353.21, 354.54, 355.2 , 355.36, 355.76, 356.85, 358.16,
       358.3 , 359.18, 359.56, 359.9 , 360.  , 363.13])

In [74]:
len(c)

30

In [75]:
np.var(c)#方差

50.126517888888884

In [76]:
np.max(h)

364.9

In [77]:
np.min(i)

333.53

In [78]:
np.diff(c)/c[:-1]#diff 相邻数组元素的差值

array([ 0.00958048,  0.01682777, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 ,  0.00943503,  0.00833333, -0.01010721,  0.00651548,
        0.00652935,  0.00200457,  0.00897472, -0.01330102, -0.02160201,
       -0.03408832,  0.01184253,  0.00075886,  0.01539897,  0.01450483,
       -0.01104159,  0.00804443,  0.02112916,  0.00122372, -0.01288889,
        0.00112562, -0.00924781, -0.0164553 ,  0.01534601])

In [79]:
np.diff(np.log(c))#对数的差=相除的对数

array([ 0.00953488,  0.01668775, -0.00205991, -0.00255903,  0.00887039,
        0.01540739,  0.0093908 ,  0.0082988 , -0.01015864,  0.00649435,
        0.00650813,  0.00200256,  0.00893468, -0.01339027, -0.02183875,
       -0.03468287,  0.01177296,  0.00075857,  0.01528161,  0.01440064,
       -0.011103  ,  0.00801225,  0.02090904,  0.00122297, -0.01297267,
        0.00112499, -0.00929083, -0.01659219,  0.01522945])

In [80]:
c = np.loadtxt('data.csv', delimiter=',', usecols=(6), unpack=True)

In [81]:
returns = np.diff(c)/c[:-1]
np.where(returns>0)

(array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
        25, 28]),)

In [90]:
logreturns = np.diff(np.log(c))
#年波动率=对数收益率的标准差（std）/对数收益率的均值（mean）/交易日倒数（1/252）
np.std(logreturns)/np.mean(logreturns)/np.sqrt(1./252.)

129.27478991115132

In [91]:
def datestr2num(s):
    return datetime.datetime.strptime(s.decode("utf-8") , "%d-%m-%Y").date().weekday()

In [94]:
#monday=0
dates, close = np.loadtxt('data.csv', delimiter=',', converters={1:datestr2num}, usecols=(1,6),  unpack=True)
dates

array([4., 0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 0., 1., 2., 3., 4., 1.,
       2., 3., 4., 0., 1., 2., 3., 4., 0., 1., 2., 3., 4.])

In [97]:
averages = np.zeros(5)
for i in range(5):
    indices = np.where(dates == i)
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print("day",i,"prices",prices,"average",avg)
    averages[i] = avg

print("highest average", np.max(averages))
print("top day of the week", np.argmax(averages))
print("lowest average", np.min(averages))
print("bottom day of the week", np.argmin(averages))

day 0 prices [[339.32 351.88 359.18 353.21 355.36]] average 351.7900000000001
day 1 prices [[345.03 355.2  359.9  338.61 349.31 355.76]] average 350.63500000000005
day 2 prices [[344.32 358.16 363.13 342.62 352.12 352.47]] average 352.1366666666666
day 3 prices [[343.44 354.54 358.3  342.88 359.56 346.67]] average 350.8983333333333
day 4 prices [[336.1  346.5  356.85 350.56 348.16 360.   351.99]] average 350.0228571428571
highest average 352.1366666666666
top day of the week 2
lowest average 350.0228571428571
bottom day of the week 4
