In [2]:
import numpy as np

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.array([1, 2, 3, 4, 5, 6], ndmin=2)

array([[1, 2, 3, 4, 5, 6]])

In [8]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [10]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
[str(c) for c in list(range(10))]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
[type(item) for item in [True, "2", 3.0, 4]]

[bool, str, float, int]

In [13]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3, 5), 17)

array([[17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17]])

In [18]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [22]:
np.random.random((3, 3)) # 3*3 0-1 均匀分布的随机数

array([[0.97480653, 0.32739816, 0.35564902],
       [0.32082953, 0.10707862, 0.53800569],
       [0.61709524, 0.97107431, 0.47922863]])

In [23]:
np.random.normal(0, 1, (3, 3))  # 3*3 均值为0， 方差为1，正态分布的随机数

array([[-0.34511845,  0.56415296, -0.36957853],
       [-1.86908058, -0.91232528,  1.10355653],
       [-0.45465966, -1.26145178,  0.3626023 ]])

In [24]:
np.random.randint(0, 10, (3, 3)) # 0到10之间，随机整数

array([[8, 0, 1],
       [5, 2, 0],
       [4, 8, 9]])

In [25]:
np.eye(3) # 单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])